baseURL = 'http://udemai.github.io/'
languageCode = 'en-us'
title = 'UdeM AI'
theme = "mini"
defaultContentLanguage = "fr"
themesDir = "../../"
hasCJKLanguage = true
paginate = 3
googleAnalytics = "your-google-analytics-id"
disqusShortname = "your-disqus-shortname"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[social]
# github = "your-github-link"
# twitter = "your-github-link"
# stackoverflow = "your-github-link"

[params]
author = ""
bio = ""
description = ""
enableRSS = false
enableComments = false
enableGoogleAnalytics = true
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = " "


[taxonomies]
   tag = "tags"
   category = "categories"


[module]
[[module.imports]]
    path = "github.com/nodejh/hugo-theme-mini"


